import Prism from 'prismjs';
import 'prismjs/themes/prism.css';
import 'prismjs/components/prism-typescript.min';
import 'prismjs/components/prism-json.min';
import 'prismjs/components/prism-jsonp.min';
import 'prismjs/components/prism-bash.min';
import 'prismjs/components/prism-java.min';
import 'prismjs/components/prism-kotlin.min';
import 'prismjs/components/prism-yaml.min';
import 'prismjs/components/prism-docker.min';
import 'prismjs/components/prism-sql.min';
import 'prismjs/components/prism-groovy.min';
import 'prismjs/components/prism-markup-templating.min';
import 'prismjs/components/prism-php.min';
import 'prismjs/components/prism-c.min';
import 'prismjs/components/prism-cpp.min';
import 'prismjs/components/prism-csharp.min';
import 'prismjs/components/prism-python.min';
import 'prismjs/components/prism-swift.min';
import 'prismjs/components/prism-go.min';

export { Prism };
export * from 'prismjs';
